# Generated by Django 6.0.6 on 2026-08-08 02:35

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kerberos', '0002_agendamento_atualizado_em_agendamento_criado_em_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='agendamento',
            options={'ordering': ['-data'], 'verbose_name': 'Agendamento', 'verbose_name_plural': 'Agendamentos'},
        ),
        migrations.AlterModelOptions(
            name='endereco',
            options={'verbose_name': 'Endereço', 'verbose_name_plural': 'Endereços'},
        ),
        migrations.AlterModelOptions(
            name='pet',
            options={'ordering': ['nome'], 'verbose_name': 'Pet', 'verbose_name_plural': 'Pets'},
        ),
        migrations.AlterModelOptions(
            name='servico',
            options={'ordering': ['nome'], 'verbose_name': 'Serviço', 'verbose_name_plural': 'Serviços'},
        ),
        migrations.AlterModelOptions(
            name='usuario',
            options={'ordering': ['nome'], 'verbose_name': 'Usuário', 'verbose_name_plural': 'Usuários'},
        ),
        migrations.AlterField(
            model_name='endereco',
            name='cep',
            field=models.CharField(max_length=9, validators=[django.core.validators.RegexValidator(message='CEP inválido. Use o formato 00000-000.', regex='^\\d{5}-?\\d{3}$')]),
        ),
        migrations.AlterField(
            model_name='endereco',
            name='numero',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1, message='O número deve ser maior que zero.')]),
        ),
        migrations.AlterField(
            model_name='pet',
            name='idade',
            field=models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(40, message='Idade informada parece inválida.')]),
        ),
        migrations.AlterField(
            model_name='servico',
            name='valor',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'), message='O valor deve ser maior que zero.')]),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='telefone',
            field=models.CharField(max_length=15, validators=[django.core.validators.RegexValidator(message='Informe um telefone válido. Ex: (11) 91234-5678 ou 11912345678.', regex='^\\(?\\d{2}\\)?[\\s-]?\\d{4,5}-?\\d{4}$')]),
        ),
    ]
